# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5092c2f0903bfe89b001c4f9bef5a75095cd2a046869781b4feec37ec0436d105fac01abaea8338264c633e20f8a173b5735f10425e28d95a1edcd5e3239879

test:
  secret_key_base: 79042978dd67af617e9b5f01d99dfd64b787edaa6f06ff6aacb276affcee8caec65c337c3a5e1782ccfc09b3e9e31252366c30d86cd7f96c4aa51d4ab4f71351

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
